"""
Django settings for business_tier_application project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ''

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'rest_framework', 
    'main_app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'business_tier_application.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'business_tier_application.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

# Configuration for Sites framework:
SITE_ID = 1

AUTH_USER_MODEL = 'main_app.BaseUser'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAdminUser',
    )
}

###############################################################################
# Parameters for Celery queueing
###############################################################################
CELERY_BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

###############################################################################
# Parameters for the QBRC mailbox
###############################################################################
MAIL_HOST = ''
MAIL_PORT = 993
MAIL_USERNAME = ''
MAIL_PASSWORD = ''
MAIL_FOLDER_NAME = 'INBOX'

# some dummy emails for testing purposes.  If an email function is invoked
# with any of these emails, it will not actually try to send.
TEST_PI_EMAIL = 'pi_email@foo.com'
TEST_ANOTHER_PI_EMAIL = 'another_pi_email@foo.com'
TEST_POSTDOC_EMAIL = 'postdoc_email@foo.com'
TEST_GRAD_STUDENT_EMAIL = 'grad_student@foo.com'
TEST_FINANCE_EMAIL = 'finance@foo.com'
TEST_EMAIL_ADDRESSES = [TEST_PI_EMAIL, TEST_FINANCE_EMAIL, TEST_POSTDOC_EMAIL, TEST_GRAD_STUDENT_EMAIL, TEST_ANOTHER_PI_EMAIL]

QBRC_EMAIL = 'qbrc@hsph.harvard.edu'

EMAIL_CREDENTIALS_FILE = '/www/credentials/final.json'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')


# For creating CNAP projects:
CNAP_URL = ''
CNAP_TOKEN = ''

# the url for the url to request a pipeline (including https://...)
QUALTRICS_PIPELINE_CREATION_URL = ''

# the password to access that request url:
QUALTRICS_PIPELINE_CREATION_PWD = ''